apiVersion: apps/v1
kind: Deployment
metadata:
  name: test66
  labels:
    app: test66
  namespace: namespace-workflow-1684288207977
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test66
  template:
    metadata:
      labels:
        app: test66
    spec:
      containers:
        - name: test66
          image: acrworkflow1684288207977.azurecr.io/image-workflow-1684288207977:latest
          ports:
            - containerPort: 3000