apiVersion: apps/v1
kind: Deployment
metadata:
  name: test3
  labels:
    app: test3
  namespace: namespace-workflow-1684288475678
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test3
  template:
    metadata:
      labels:
        app: test3
    spec:
      containers:
        - name: test3
          image: acrworkflow1684288475678.azurecr.io/image-workflow-1684288475678:latest
          ports:
            - containerPort: 3000