apiVersion: apps/v1
kind: Deployment
metadata:
  name: TEST5
  labels:
    app: TEST5
  namespace: namespace-workflow-1684286869611
spec:
  replicas: 1
  selector:
    matchLabels:
      app: TEST5
  template:
    metadata:
      labels:
        app: TEST5
    spec:
      containers:
        - name: TEST5
          image: acrworkflow1684286869611.azurecr.io/image-workflow-1684286869611:latest
          ports:
            - containerPort: 3000