apiVersion: v1
kind: Service
metadata:
  name: TEST5
  namespace: namespace-workflow-1684286869611
spec:
  type: LoadBalancer
  selector:
    app: TEST5
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000