apiVersion: v1
kind: Service
metadata:
  name: test66
  namespace: namespace-workflow-1684288207977
spec:
  type: LoadBalancer
  selector:
    app: test66
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000